global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'simple_app'
    static_configs:
      - targets: ['simple_app:8080']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules"
